meta:
  engine: 4.1.0
units:
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
points:
  key.tags:
    - key
  zones:
    matrix:
      key:
        padding: 1py
        spread: 1px
      columns:
        outer:
        pinky:
        ring.key: 
          origin: [-12, -19]
          stagger: 10
        middle.key:
          stagger: 5
        index.key:
          stagger: -6
        inner.key:
          stagger: -2
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-20, -19]
      columns:
        near:
        home.key:
          stagger: -2.7
          spread: cx + 2
          splay: -10
        far.key:
          width: 1.5kx
          splay: 80
          stagger: 2
          spread: cx + 3.5
          tags:
            - key_1_5u
      rows:
        thumb:
    mcu:
      key.tags:
        - helper
      anchor:
        - ref: matrix_inner_top
          shift: [kx/2+18/2+1.6,ky/2-33/2]
    display:
      key.tags:
        - helper
      anchor:
        - ref: mcu
          shift: [0,-3.5]
outlines:
  _keycaps:
    - what: rectangle
      where: [key]
      size: 18
      fillet: 3
    - what: rectangle
      where: [key_1_5u]
      size: [kx*1.5,ky]
      fillet: 3
  _mcu:
    - what: rectangle
      where: [mcu]
      size: [17.78,33]
      fillet: 1
    - what: rectangle
      where: [mcu]
      size: [8.94,7.35]
      fillet: 0.1
      operation: stack
      adjust:
        shift: [0,33/2-7.35/2+0.7]
  _display:
    - what: rectangle
      where: [display]
      size: [14,36]
      fillet: 0.5
    - what: rectangle
      where: [display]
      size: [12.82,2.66]
      operation: stack
      fillet: 0.1
      adjust:
        shift: [0,-16.7]
    - what: rectangle
      where: [display]
      size: [10.8,24.6]
      operation: stack
      adjust:
        shift: [0,-0.75]
  _mcu_cluster:
    - what: outline
      name: _mcu
      operation: stack
    - what: outline
      name: _display
      operation: stack
  keyboard:
    - what: rectangle
      where: [key]
      size: [kx,ky]
      operation: stack
    - what: rectangle
      where: [key_1_5u]
      size: [1.5kx,ky]
    - what: rectangle
      where: [mcu]
      size: [18,33]
    - what: rectangle
      where: [display]
      size: [18, 36]
