# Enable the display
CONFIG_ZMK_DISPLAY=y

# Enable the battery widget and ask it to show percentage
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# Enable the layer widget
CONFIG_ZMK_WIDGET_LAYER_STATUS=y

# Enable the Bluetooth/Output status widget
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y